### ISSUE TITLE
Remove master branch?

### ISSUE THREAD

**Issue by verythorough** [girldevelopit/gdi-featured-html-css-intro#42]
In other projects where the `gh-pages` and `master` branches were identical, I've found it convenient to set `gh-pages` as the default branch, and remove `master`.  This avoids the hassle of keeping the branches synced, and prevents branch-use discrepancies like in PR #38.

**Comment by Roenok** [comment]
Not a bad idea. I'll check with the other github admins on the team and see what they think.

**Comment by Roenok** [comment]
@verythorough General consensus is that this should work, so we'll try it. Thanks!
